# Data Generation
shape_category: "abstract_animal"
data_path: "/Users/yuhanghuang/Workspaces/01.research-proj/TEBP/data/src"
data_norm_path: "/Users/yuhanghuang/Workspaces/01.research-proj/TEBP/data/norm"
data_bullet_path: "/Users/yuhanghuang/Workspaces/01.research-proj/TEBP/data/bullet"

# Cook Data
folderPath: "/Users/yuhanghuang/FractureTest/resultAndData/test/timeTest/"
workspacePath: "/Users/yuhanghuang/FractureTest/resultAndData/test/timeTest/json/"
savePath: "/Users/yuhanghuang/FractureTest/resultAndData/test/timeTest/"