#cloud-config
runcmd:
  - cd /home/azureuser/
  - wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1mqwgEX_ZgOifRBLFllqw6cGFRXwUhwk8" -O /home/azureuser/download.tar.gz
  - tar -xzvf /home/azureuser/download.tar.gz -C /home/azureuser/
  - sudo chmod +x /home/azureuser/download.sh
  - sudo /home/azureuser/download.sh
